### ISSUE TITLE
Invalid flow error while using Neo4j tasks

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-neo4j#59]
### Expected Behavior

The flow example as mentioned on the [Neo4j plugin page](https://kestra.io/plugins/tasks/io.kestra.plugin.neo4j.query) should work seamlessly with proper placeholder values.

### Actual Behaviour

When I was trying out the flow as mentioned on the [Neo4j plugin page](https://kestra.io/plugins/tasks/io.kestra.plugin.neo4j.query), the flow errors out while trying to save. 

![Screenshot 2024-03-14 at 11 38 52 AM](https://github.com/kestra-io/plugin-neo4j/assets/6594483/2ab906c5-ff18-49cc-a43b-18c3ab0212b8)

The error states "Illegal flow yaml".

The same error comes up with other Neo4j task(https://kestra.io/plugins/tasks/io.kestra.plugin.neo4j.batch) as well.

### Steps To Reproduce

Create the same flow as stated on the plugin page with appropriate values. Save the flow. You will not be able to save the flow as an error would start appearing.

### Environment Information

- Kestra Version: 0.15.0
- Plugin version: 0.15.0
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

id: "query"
type: "io.kestra.plugin.neo4j.Query"
url: "{{url}}"
username: "{{username}}"
password: "{{password}}"
query: |
   MATCH (p:Person)
   RETURN p
storeType: FETCH

**Comment by loicmathieu** [comment]
I tested it and it works.
I suspect some plugin issue at that time that is fixed now.
